### ISSUE TITLE
no module named configparser

### ISSUE THREAD

**Issue by nvanderperren** [rogerhoward/iiify#3]
I can't start iiify. I always get following error.

MacBook-Pro-van-Nastasia:iiify nastasia$ python app.py
/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'app.py': [Errno 2] No such file or directory
MacBook-Pro-van-Nastasia:iiify nastasia$ cd niiifty
MacBook-Pro-van-Nastasia:niiifty nastasia$ python app.py
Traceback (most recent call last):
  File "app.py", line 7, in <module>
    from configs import options, cors, approot, cache_root, media_root, cache_expr
  File "/Users/nastasia/iiify/niiifty/configs/__init__.py", line 15, in <module>
    import configparser
ImportError: No module named configparser

**Comment by rogerhoward** [comment]
Thanks - will look into it. This project isn't currently maintained, was just a weekend hack I built as a teaching object, and then accepted a pull request with some improvements later. It's not up to production quality, so unless you're willing to hack on it yourself I'd recommend Loris or other IIIF servers for day to day.
